import type { Category } from "./constants/customAiCategories";
import type { FaqItem } from "./constants/faqList";
import type { ProcessStep } from "./constants/processSteps";
import type { ReasonItem } from "./constants/reasonItem";

export type Language = "ko" | "en";

export const getLanguage = (language: string): Language => language.startsWith("en") ? "en" : "ko";

export const footerContent = {
    ko: {
        terms: "서비스 이용약관",
        privacy: "개인정보처리방침",
        ceo: "대표 : 신동민",
        businessNumber: "사업자등록번호 : 225-10-15800",
        email: "이메일 : dongmin@amuse8.kr",
        address: "주소 : 서울특별시 동작구 흑석로 93-1, 동작스타트업센터, 101호",
        copyright: "All rights reserved",
    },
    en: {
        terms: "Terms of Service",
        privacy: "Privacy Policy",
        ceo: "CEO: Dongmin Shin",
        businessNumber: "Business Registration No.: 225-10-15800",
        email: "Email: dongmin@amuse8.kr",
        address: "Address: 101, Dongjak Startup Center, 93-1 Heukseok-ro, Dongjak-gu, Seoul, Korea",
        copyright: "All rights reserved",
    },
} as const;

export const aboutContent = {
    ko: {
        seoDescription: "Amuse8의 비전과 히스토리, 그리고 우리가 만드는 AI 제품/솔루션을 소개합니다.",
        scroll: "Scroll",
        scrollDown: "scroll down",
        introEn: "At Amuse8, we build AI inspired by our own muse,\nwith the mission of automating information management.",
        introKo: "Amuse8(아뮤즈8)은 ‘정보관리 자동화’를 미션으로,\n우리만의 영감을 담은 AI를 만듭니다.",
        dataDiscovers: ["Data discovers", "your Possibilities"],
        possibilityTitle: "AI는 데이터(Data) 속에 숨은 가능성(Possibility)을 현실로 바꾸는 가장 확장적인 기술입니다.",
        possibilityBody: [
            "오늘의 기업들은 복잡한 데이터와 비효율적인 시스템 속에서 무엇이 문제인지, 어떻게 AI를 적용해야 하는지조차 알기 어려운 상황에 놓여 있습니다.",
            "Amuse8은 이 간극을 메웁니다.",
            "우리는 사용자의 경험을 중심에 두고, 정보를 분석해 잠재력을 발견하며 필요한 순간 바로 활용할 수 있는 AI 제품을 만들어 갑니다.",
            "모든 기업이 AI의 가능성을 현실로 바꿀 수 있는 세상을 만들어 갑니다.",
        ],
        future: "Amuse8는 모두가\nAI의 가능성을 활용할 수 있는\n미래를 만듭니다.",
        problemTitle: "AI 적용의 난제",
        problemTitleMobile: "막막한 AI 적용",
        problemBody: "AI 기술은 빠르게 발전하는데,\n왜 기업은 여전히 어려움을 겪을까요?\n복잡한 데이터와 시스템 속에서 문제를 파악하기 어렵고,\nAI의 실제 업무 적용 방식도 명확하지 않기 때문입니다.",
        solutionTitle: "명확한 AI 해법",
        solutionTitleMobile: "손쉬운 AI 경험",
        solutionBody: "Amuse8은 문제를 먼저 정의하고,\n그에 가장 적합한 AI 해결책을 제품 형태로 제공합니다.\n누구나 필요한 순간 바로 사용할 수 있는 실질적인 AI 경험을 만드는 것이 우리의 방식입니다.",
        productLabel: "Our Product",
        productTitle: "직접 경험해 보세요",
        productBody: "AI로 비즈니스의 한계를 넘어서고 싶다면,\n지금 Amuse8과 함께 무한한 AI 경험을 시작해보세요.",
        blokitCard: "흩어진 정보를\n즉시 활용 가능한 지식으로 바꿉니다.",
        customCard: "비즈니스에 필요한 AI를\n원하는 형태로 만들어 드립니다.",
        moreBlokit: "Blokit AI 더 알아보기",
        moreCustom: "Custom AI 더 알아보기",
        contact: "문의하기",
    },
    en: {
        seoDescription: "Explore Amuse8's vision, history, and the AI products and solutions we build.",
        scroll: "Scroll",
        scrollDown: "scroll down",
        introEn: "At Amuse8, we build AI inspired by our own muse,\nwith the mission of automating information management.",
        introKo: "We turn information management into automated AI experiences\ninspired by our own muse.",
        dataDiscovers: ["Data discovers", "your Possibilities"],
        possibilityTitle: "AI is the most scalable technology for turning hidden possibilities in data into reality.",
        possibilityBody: [
            "Companies today face complex data and inefficient systems, making it hard to identify the real problem or decide how to apply AI.",
            "Amuse8 closes that gap.",
            "We center the user experience, analyze information to uncover potential, and build AI products that can be used exactly when they are needed.",
            "We are building a future where every company can turn the possibilities of AI into reality.",
        ],
        future: "Amuse8 builds a future\nwhere everyone can use\nthe possibilities of AI.",
        problemTitle: "The AI Adoption Challenge",
        problemTitleMobile: "Difficult AI Adoption",
        problemBody: "AI technology is advancing quickly,\nso why do companies still struggle?\nIt is difficult to identify the right problem inside complex data and systems,\nand the practical way to apply AI to work is often unclear.",
        solutionTitle: "Clear AI Solutions",
        solutionTitleMobile: "Practical AI Experience",
        solutionBody: "Amuse8 defines the problem first,\nthen provides the most suitable AI solution as a product.\nOur approach is to create practical AI experiences anyone can use when they need them.",
        productLabel: "Our Product",
        productTitle: "Experience it directly",
        productBody: "If you want to move beyond the limits of your business with AI,\nstart an infinite AI experience with Amuse8.",
        blokitCard: "Turn scattered information\ninto knowledge ready to use.",
        customCard: "Build the AI your business needs\nin the exact form you want.",
        moreBlokit: "Learn more about Blokit AI",
        moreCustom: "Learn more about Custom AI",
        contact: "Contact Us",
    },
} as const;

export const blokitContent = {
    ko: {
        seoDescription: "Blokit은 문서와 데이터를 자동으로 정리·태깅하고, 필요한 정보를 빠르게 찾을 수 있도록 돕는 AI 기반 문서·데이터 관리 시스템입니다.",
        heroTitle: "흩어진 정보를, 쓸 수 있는 자산으로",
        heroSubtitle: "Turning scattered information into usable assets",
        heroCta: "우리 회사 시스템에 Blokit AI 도입하기",
        introTitle: "정보 과잉 시대,\n당신의 디지털 기억력은 안녕하신가요?",
        introBody: "하루 평균 100개 이상의 알림, 수십 개의 탭, 끝없는 스크롤 속에서 정작 중요한 것은 기억나지 않습니다.",
        stats: [
            ["82%", "직장인이 정보 과잉을 경험"],
            ["4.5시간", "하루 평균 정보 수집 시간"],
            ["63%", "수집한 정보를 잊어버림"],
        ],
        enterpriseTitle: "이러한 문제는\n기업에서 더욱 심각합니다",
        enterpriseBody1: "직장인 72.6%가 업무 자료 관리에 어려움을 겪고 있으며",
        enterpriseBody2: "관리되지 않은 수많은 자료로 인해 35.8%의 업무 효율이 저하되고 있습니다.",
        lossesTitle: "비효율적 자료 관리가 가져오는 손실",
        losses: [
            ["시간적 손실", "주 평균 18시간 이상 낭비"],
            ["생산성 손실", "업무 생산성 20% 감소"],
            ["비용적 손실", "연간 약 3천만원 낭비"],
        ],
        source: "출처 Freepik",
        smartLead: "복잡한 자료 3초만에 정리 끝!",
        smartTitle: "가장 스마트한\nAI API Blokit",
        tags: ["#자동 라벨링", "#자동 분류", "#자동 정리", "#문서 분석", "#태그 요약", "#유사 정보 통합", "#부분 스크랩", "#빠른 검색", "#키워드 추출"],
        smartBody: "AI가 자동으로 분류하고 정리하여\n필요한 정보를 더 쉽게 찾을 수 있습니다.",
        dragTitle: "한번의 드래그로\n한번에 정리",
        dragBody: "AI가 문서를 분석하고, 적합한 카테고리로 정리합니다.\n더 효율적인 작업 환경을 경험해보세요.",
        solutionTitle: "업무 효율을 높이는 똑똑한 솔루션",
        b2bItems: ["업무 효율 극대화", "시간 및 비용 절감", "SaaS 관리 간소화 및 다중 결제 문제 해결"],
        resultTitle: "기술력 기반의 확실한 성과",
        laborTitle: "인건비 감소 또는 대체",
        before: "기존",
        after: "서비스 도입",
        timeBefore: "24시간",
        timeAfter: "약 20분",
        teamBefore: "팀 단위",
        teamAfter: "1명",
        inquiryLabel: "Blokit AI 도입 문의",
        inquiryTitle: "우리 회사 시스템에 Blokit AI 도입하기",
        inquiryBody: "현재 업무 흐름에 맞춰 연동/도입 방식을 함께 설계해드립니다.",
        inquiryButton: "문의하기로 이동",
        dataTitle: "자사는 사용자의 데이터 소유권을 절대 주장하지 않습니다.",
        dataBody: "Blokit은 사용자의 데이터를 AI 기능 개선을 위한 용도로만 활용하며, 다른 목적으로 이를 활용하지 않습니다.",
    },
    en: {
        seoDescription: "Blokit is an AI-powered document and data management system that organizes, tags, and helps teams find the information they need quickly.",
        heroTitle: "Turn scattered information into usable assets",
        heroSubtitle: "Turning scattered information into usable assets",
        heroCta: "Introduce Blokit AI to your company system",
        introTitle: "In the age of information overload,\nhow is your digital memory holding up?",
        introBody: "With over 100 notifications a day, dozens of tabs, and endless scrolling, the important things are often the first to disappear.",
        stats: [
            ["82%", "workers experience information overload"],
            ["4.5 hours", "average daily time spent collecting information"],
            ["63%", "forget information they collected"],
        ],
        enterpriseTitle: "The problem becomes\nmore serious inside companies",
        enterpriseBody1: "72.6% of workers struggle with managing work materials",
        enterpriseBody2: "and unmanaged documents reduce work efficiency by 35.8%.",
        lossesTitle: "The cost of inefficient document management",
        losses: [
            ["Time Loss", "Over 18 hours wasted each week"],
            ["Productivity Loss", "20% decrease in work productivity"],
            ["Cost Loss", "About KRW 30M wasted annually"],
        ],
        source: "Source Freepik",
        smartLead: "Organize complex materials in 3 seconds",
        smartTitle: "The smartest\nAI API Blokit",
        tags: ["#Auto Labeling", "#Auto Classification", "#Auto Organization", "#Document Analysis", "#Tag Summary", "#Similar Info Merge", "#Partial Scrap", "#Fast Search", "#Keyword Extraction"],
        smartBody: "AI automatically classifies and organizes documents\nso you can find the information you need faster.",
        dragTitle: "One drag,\norganized all at once",
        dragBody: "AI analyzes documents and sorts them into the right categories.\nExperience a more efficient work environment.",
        solutionTitle: "A smart solution that improves work efficiency",
        b2bItems: ["Maximize work efficiency", "Reduce time and cost", "Simplify SaaS management and solve multiple payment issues"],
        resultTitle: "Clear results powered by technology",
        laborTitle: "Reduce or replace labor cost",
        before: "Before",
        after: "After adoption",
        timeBefore: "24 hours",
        timeAfter: "About 20 min",
        teamBefore: "Team",
        teamAfter: "1 person",
        inquiryLabel: "Blokit AI adoption inquiry",
        inquiryTitle: "Introduce Blokit AI to your company system",
        inquiryBody: "We design the right integration and adoption path for your current workflow.",
        inquiryButton: "Go to inquiry",
        dataTitle: "We never claim ownership of user data.",
        dataBody: "Blokit uses user data only to improve AI features and does not use it for any other purpose.",
    },
} as const;

export const customContent = {
    ko: {
        seoDescription: "Amuse8은 기업의 목적과 환경에 맞춰 모델, 데이터, 시스템을 설계하고 실서비스에 적용 가능한 맞춤형 AI 솔루션을 제공합니다.",
        heroTitle: "필요한 AI가 있으신가요?",
        heroBody: "원하는 기능을, 원하는 형태로 제작해 드립니다.",
        reasonsTitle: "Custom AI가 필요한 이유는 분명합니다",
        problemLabel: "문제 상황",
        solutionLabel: "해결 방안",
        hoverHint: "마우스를 올려보세요",
        tapHint: "탭해서 내용을 확인해보세요",
        designBadge: "Custom AI by Amuse8",
        designTitle: "Amuse8은\n상황에 맞는 AI를 설계합니다",
        designBody: "특정 모델/기능에 갇히지 않고,\n목표·데이터·예산·일정에 맞춰 가장 적합한 조합으로 구현합니다.",
        designCards: [["목표 중심 설계", "필요한 성과부터 정의합니다."], ["빠른 PoC", "검증 후 확장으로 리스크를 줄입니다."], ["운영까지 고려", "배포·모니터링·개선까지 연결합니다."]],
        processTitle: "프로세스는\n이렇게 진행됩니다",
        ctaLead: "상담이 필요하신가요?",
        ctaTitle: "어떤 AI가 필요한지 모르셔도\n괜찮습니다",
        ctaBody: "비즈니스 상황에 가장 적합한 AI 활용 방법을\n명확하게 안내해드립니다.",
        ctaButton: "문의하기",
    },
    en: {
        seoDescription: "Amuse8 designs models, data, and systems around each company's goals and environment, delivering custom AI solutions ready for real services.",
        heroTitle: "Do you need a specific AI?",
        heroBody: "We build the features you want in the form you need.",
        reasonsTitle: "There are clear reasons to choose Custom AI",
        problemLabel: "Problem",
        solutionLabel: "Solution",
        hoverHint: "Hover to view",
        tapHint: "Tap to view",
        designBadge: "Custom AI by Amuse8",
        designTitle: "Amuse8 designs AI\nfor your exact situation",
        designBody: "We are not locked into a specific model or feature.\nWe build the best combination for your goals, data, budget, and timeline.",
        designCards: [["Goal-first design", "We define the outcome before the technology."], ["Fast PoC", "Validate first, then scale with lower risk."], ["Built for operations", "Deployment, monitoring, and improvement are connected."],
        ],
        processTitle: "The process\nworks like this",
        ctaLead: "Need a consultation?",
        ctaTitle: "Even if you are not sure\nwhich AI you need, that is okay",
        ctaBody: "We clearly guide you toward the best way to use AI\nfor your business situation.",
        ctaButton: "Contact Us",
    },
} as const;

export const customReasons: Record<Language, ReasonItem[]> = {
    ko: [
        { id: "reason-1", problem: "고정 비용과 \n비효율적인 리소스 운영", solution: "유연한 비용 구조와\n 리소스 활용" },
        { id: "reason-2", problem: "느린 실행과 \n반복되는 시행착오", solution: "빠른 실행과 \n검증된 경험" },
        { id: "reason-3", problem: "기술 중심의 선택으로 인한 \n방향성 혼란", solution: "목적에 맞는 \n기술 조합" },
        { id: "reason-4", problem: "조직 확장에 따른 \n리스크 증가", solution: "조직 확장 없는 \n리스크 관리" },
    ],
    en: [
        { id: "reason-1", problem: "Fixed costs and\ninefficient resource operations", solution: "Flexible cost structure\nand resource usage" },
        { id: "reason-2", problem: "Slow execution and\nrepeated trial and error", solution: "Fast execution and\nproven experience" },
        { id: "reason-3", problem: "Direction confusion from\ntechnology-first choices", solution: "Technology combinations\nmatched to the goal" },
        { id: "reason-4", problem: "Higher risk from\norganizational expansion", solution: "Risk management without\nexpanding the organization" },
    ],
};

export const customCategories: Record<Language, Category[]> = {
    ko: [
        { id: "data-business", label: "데이터/비즈니스", examples: [{ title: "대량 데이터 자동 수집·정제", description: "여러 소스의 데이터를 자동으로 모아 정리해, 바로 활용 가능한 형태를 제공합니다." }, { title: "비즈니스 지표 예측", description: "패턴을 분석해 주요 지표를 예측하고 의사결정에 필요한 인사이트를 제공합니다." }, { title: "업무 프로세스 자동화", description: "반복 업무를 자동 처리해 효율을 높이고 작업 시간을 줄여줍니다." }] },
        { id: "vision-video", label: "비전/영상", examples: [{ title: "이미지·영상 품질 보정", description: "저해상도나 노이즈가 있는 영상·이미지를 자동으로 개선해 선명한 품질로 복원합니다." }, { title: "영상 분석", description: "영상 속 주요 장면, 패턴, 이벤트를 자동으로 분석해 필요한 정보를 추출합니다." }, { title: "객체/행동 인식", description: "사람·사물·행동을 정확하게 인식해 상황 파악과 자동화된 처리에 활용할 수 있습니다." }, { title: "자동 자막 생성", description: "음성을 분석해 빠르고 정확하게 자막을 생성하며, 편집에 필요한 후처리까지 지원합니다." }] },
        { id: "recommendation", label: "추천/개인화", examples: [{ title: "개인화 상품 추천 시스템", description: "사용자의 구매 기록, 검색 패턴, 관심 카테고리를 분석해 가장 관련성 높은 상품을 자동으로 추천합니다." }, { title: "콘텐츠 개인화 추천 엔진", description: "이용자의 시청·읽기 습관을 기반으로 선호 콘텐츠를 파악해, 개별 사용자에게 최적화된 콘텐츠를 우선 노출합니다." }, { title: "상황·시간대 기반 추천 모델", description: "사용자의 시간대, 위치, 사용 맥락을 반영해 상황에 맞는 상품·콘텐츠·기능을 제안합니다." }] },
        { id: "nlp-audio", label: "자연어/음성", examples: [{ title: "문서 자동 작성·요약", description: "긴 문서나 대화 내용을 자동으로 정리해 핵심만 빠르게 파악할 수 있도록 작성·요약합니다." }, { title: "상담·QA 챗봇", description: "반복되는 문의를 자동으로 응답하며, 필요한 정보를 정확하게 안내하는 상담형 챗봇을 제공합니다." }, { title: "음성 인식(STT)·음성 생성(TTS)", description: "음성을 텍스트로 전환하거나 자연스러운 음성으로 생성해, 다양한 서비스에서 음성 기반 인터페이스를 구현할 수 있습니다." }] },
        { id: "robotics", label: "로보틱스", examples: [{ title: "경로 최적화", description: "주어진 환경에서 가장 효율적인 이동 경로를 계산해 이동 시간과 비용을 최소화합니다." }, { title: "로봇 제어 모델", description: "로봇의 움직임과 작업 수행을 안정적으로 제어할 수 있는 모델을 구축해 정밀한 동작을 구현합니다." }, { title: "작업 자동화 및 위치 기반 판단 알고리즘", description: "로봇이 주변 환경을 파악해 필요한 작업을 자동으로 수행하고, 상황에 맞는 판단을 내릴 수 있도록 지원합니다." }] },
        { id: "multimodal", label: "멀티모달", examples: [{ title: "텍스트·이미지·영상 융합 분석", description: "여러 형태의 데이터를 함께 분석해, 단일 데이터로는 파악하기 어려운 패턴과 의미를 도출합니다." }, { title: "검색·추천 고도화", description: "텍스트, 이미지, 영상 정보를 동시에 활용해 더 정확하고 정교한 검색·추천 결과를 제공합니다." }, { title: "상황 기반 응답 생성", description: "사용자의 입력 유형과 상황을 함께 고려해, 가장 적합한 형태의 응답을 생성합니다." }] },
        { id: "app-web", label: "APP/WEB", examples: [{ title: "UI 자동 생성", description: "요구사항과 디자인 가이드를 기반으로 화면 요소를 자동으로 구성해 개발 속도를 높입니다." }, { title: "사용자 행동 분석", description: "사용자의 클릭, 이동 경로, 이용 패턴을 분석해 서비스 개선에 필요한 인사이트를 제공합니다." }, { title: "서비스 운영 자동화 및 A/B 테스트 최적화", description: "운영 작업을 자동화하고, 실험 결과를 분석해 가장 효과적인 서비스 버전을 빠르게 검증합니다." }] },
        { id: "crm-erp", label: "CRM/ERP", examples: [{ title: "고객 세그먼트 분석", description: "고객의 행동과 특성을 기반으로 그룹을 자동 분류해, 타겟 마케팅과 맞춤 전략 수립을 지원합니다." }, { title: "판매·수요 예측", description: "과거 데이터와 패턴을 분석해 향후 매출과 수요를 예측하고, 재고·생산 계획을 효율적으로 세울 수 있도록 돕습니다." }, { title: "재고·운영 자동화 및 의사결정 보조", description: "재고 관리와 운영 업무를 자동화하고, 의사결정에 필요한 핵심 지표를 실시간으로 제공합니다." }] },
    ],
    en: [
        { id: "data-business", label: "Data/Business", examples: [{ title: "Automated large-scale data collection and cleansing", description: "Automatically collect and organize data from multiple sources into a usable format." }, { title: "Business metric forecasting", description: "Analyze patterns to forecast key indicators and provide decision-making insights." }, { title: "Workflow automation", description: "Automate repetitive work to improve efficiency and reduce task time." }] },
        { id: "vision-video", label: "Vision/Video", examples: [{ title: "Image and video quality enhancement", description: "Restore low-resolution or noisy media into clearer quality." }, { title: "Video analysis", description: "Analyze scenes, patterns, and events in video to extract useful information." }, { title: "Object and behavior recognition", description: "Recognize people, objects, and actions for situational understanding and automation." }, { title: "Automatic caption generation", description: "Analyze speech to create accurate captions and support post-processing for editing." }] },
        { id: "recommendation", label: "Recommendation/Personalization", examples: [{ title: "Personalized product recommendation system", description: "Recommend relevant products by analyzing purchases, searches, and interests." }, { title: "Personalized content recommendation engine", description: "Prioritize content for each user based on viewing and reading behavior." }, { title: "Context and time-based recommendation model", description: "Suggest products, content, or features based on time, location, and usage context." }] },
        { id: "nlp-audio", label: "NLP/Voice", examples: [{ title: "Automatic document writing and summarization", description: "Summarize long documents or conversations so teams can quickly understand key points." }, { title: "Support and QA chatbot", description: "Automate repeated inquiries and guide users with accurate information." }, { title: "Speech recognition and voice generation", description: "Convert speech to text or generate natural voice interfaces for services." }] },
        { id: "robotics", label: "Robotics", examples: [{ title: "Route optimization", description: "Calculate efficient movement paths to reduce time and cost." }, { title: "Robot control model", description: "Build models that control robot movement and tasks with stability and precision." }, { title: "Task automation and location-based decision algorithms", description: "Help robots understand surroundings, perform tasks, and make context-aware decisions." }] },
        { id: "multimodal", label: "Multimodal", examples: [{ title: "Text, image, and video fusion analysis", description: "Analyze multiple data types together to uncover patterns and meaning." }, { title: "Advanced search and recommendation", description: "Use text, image, and video together for more accurate search and recommendations." }, { title: "Context-aware response generation", description: "Generate the most suitable response based on input type and situation." }] },
        { id: "app-web", label: "APP/WEB", examples: [{ title: "Automatic UI generation", description: "Generate screen elements from requirements and design guides to speed development." }, { title: "User behavior analysis", description: "Analyze clicks, paths, and usage patterns to provide service improvement insights." }, { title: "Service operation automation and A/B test optimization", description: "Automate operations and analyze experiments to validate the best service version faster." }] },
        { id: "crm-erp", label: "CRM/ERP", examples: [{ title: "Customer segment analysis", description: "Automatically classify customer groups for targeted marketing and strategy." }, { title: "Sales and demand forecasting", description: "Forecast revenue and demand from historical data to improve inventory and production planning." }, { title: "Inventory and operation automation with decision support", description: "Automate inventory and operations while providing real-time decision indicators." }] },
    ],
};

export const customProcessSteps: Record<Language, ProcessStep[]> = {
    ko: [
        { id: "01", title: "문의/신청", desc: "문의하기를 통해 어떤 서비스가 필요한지 신청합니다." },
        { id: "02", title: "상담/컨설팅", desc: "전문가를 통해 우리 기업, 브랜드의 특성과 니즈에 맞춤 제작을 위해 상담 및 컨설팅 합니다." },
        { id: "03", title: "상세 견적 안내", desc: "고객 니즈를 반영한 상세 견적을 안내 드립니다." },
        { id: "04", title: "계약", desc: "발송드린 전자계약서에 서명 후 입금 절차를 진행합니다." },
        { id: "05", title: "개발", desc: "고객사의 특성과 니즈에 맞춰 전문인력이 투입되어 개발합니다." },
        { id: "06", title: "피드백 및 수정", desc: "주 1회 개발 보고와 실시간 개발 진행 상황을 확인하고 피드백을 반영해 수정합니다." },
        { id: "07", title: "프로젝트 완료", desc: "프로젝트를 종료하거나 추가 계약 여부를 조율합니다." },
    ],
    en: [
        { id: "01", title: "Inquiry", desc: "Tell us what kind of service or AI solution you need." },
        { id: "02", title: "Consulting", desc: "We consult on your company's needs, brand, and operating context." },
        { id: "03", title: "Estimate", desc: "We provide a detailed estimate based on your requirements." },
        { id: "04", title: "Contract", desc: "Proceed with e-contract signing and payment." },
        { id: "05", title: "Development", desc: "Specialists develop the solution around your requirements." },
        { id: "06", title: "Feedback", desc: "Weekly reports and real-time progress updates reflect your feedback." },
        { id: "07", title: "Completion", desc: "We close the project or discuss additional engagement." },
    ],
};

export const customFaqList: Record<Language, FaqItem[]> = {
    ko: [
        { id: "faq-1", q: "정부지원금 집행이 가능한가요 ?", a: "가능합니다. 정부지원금 집행 시 필요한 서류 준비까지 함께해요 !" },
        { id: "faq-2", q: "개발이 진행되는 과정을 볼 수 있나요 ?", a: "노션을 통해 실시간 작업 진행 현황을 확인하실 수 있으시며,\n매주 담당PM을 통한 진행 과정을 공유드립니다 !" },
        { id: "faq-3", q: "데이터 소유권은 어떻게 귀속되나요 ?", a: "작업에 대한 저작권 및 소유권, 특허 등의 권한은 일체 주장하지 않으며 (계약서에 해당내용 포함),\n또한 프로젝트 종료 후에도 고객 요청 시 데이터 반납 또는 완전 삭제를 진행합니다." },
        { id: "faq-4", q: "포트폴리오를 받을 수 있나요 ?", a: "**별도의 공개 포트폴리오는 제공하지 않습니다.**\n고객 데이터와 결과물을 외부에 노출하지 않는다는 원칙에 따른 결정입니다.\n저희는 “고객의 데이터를 끝까지 보호하는 구조”로 신뢰를 증명합니다." },
    ],
    en: [
        { id: "faq-1", q: "Can government grants be used?", a: "Yes. We also help prepare documents required for grant execution." },
        { id: "faq-2", q: "Can I see the development process?", a: "You can check real-time work progress through Notion,\nand the assigned PM shares weekly progress updates." },
        { id: "faq-3", q: "Who owns the data?", a: "We do not claim copyrights, ownership, patents, or any other rights to the work. This is included in the contract.\nAfter the project ends, we can return or permanently delete data upon request." },
        { id: "faq-4", q: "Can I receive a portfolio?", a: "**We do not provide a separate public portfolio.**\nThis follows our principle of not exposing client data or deliverables externally.\nWe prove trust through a structure that protects customer data to the end." },
    ],
};

export const inquiryContent = {
    ko: {
        seoDescription: "Amuse8과의 협업, AI 도입 및 제품·솔루션 관련 문의를 남겨주세요. 요구사항을 바탕으로 적합한 AI 방향을 제안드립니다.",
        title: "문의하기",
        privacyAgree: "개인정보 수집동의",
        viewFull: "전문보기",
        agree: "동의합니다.",
        inquiryType: "문의 유형",
        select: "선택해 주세요",
        selectHelp: "문의 목적에 맞는 항목을 선택해 주세요.",
        customCategory: "Custom AI 문의 항목",
        etc: "기타 내용",
        etcPlaceholder: "예) 사내 문서 자동 분류/권한 기반 검색 등",
        email: "이메일",
        phone: "연락처",
        message: "문의 내용",
        messagePlaceholder: "100자 이내로 입력해 주세요.",
        remaining: "자 남음",
        botHelp: "봇 방지를 위해 인증이 필요합니다.",
        submitting: "전송 중...",
        submit: "제출하기",
        companyImageAlt: "회사 이미지",
        inquiryOptions: ["Blokit AI 문의", "WallWall AI 문의", "Custom AI 문의"],
        categoryOptions: ["1. 데이터/비즈니스", "2. 비전/영상", "3. 추천/개인화", "4. 자연어/음성", "5. 로보틱스", "6. 멀티모달", "7. APP/WEB", "8. CRM/ERP", "9. 기타 : 직접 입력"],
        errors: {
            agree: "개인정보 수집·이용에 동의해 주세요.",
            type: "문의 유형을 선택해 주세요.",
            custom: "Custom AI 문의 항목을 선택해 주세요.",
            etc: "기타 항목을 입력해 주세요.",
            emailRequired: "이메일을 입력해 주세요.",
            emailInvalid: "올바른 이메일 형식으로 입력해 주세요.",
            phone: "연락처를 입력해 주세요.",
            message: "문의 내용을 입력해 주세요.",
            length: "문의 내용은 100자 이내로 입력해 주세요.",
            bot: "봇 방지 인증을 완료해 주세요.",
            blocked: "요청을 처리할 수 없습니다.",
            failed: "전송 실패. 잠시 후 다시 시도해 주세요.",
            success: "접수가 완료되었습니다. 빠르게 확인 후 연락드리겠습니다.",
        },
    },
    en: {
        seoDescription: "Contact Amuse8 about partnerships, AI adoption, products, and solutions. We suggest the right AI direction based on your requirements.",
        title: "Contact Us",
        privacyAgree: "Privacy collection consent",
        viewFull: "View full text",
        agree: "I agree.",
        inquiryType: "Inquiry type",
        select: "Please select",
        selectHelp: "Choose the option that best matches your inquiry.",
        customCategory: "Custom AI inquiry category",
        etc: "Other details",
        etcPlaceholder: "Example: internal document auto-classification / permission-based search",
        email: "Email",
        phone: "Phone",
        message: "Message",
        messagePlaceholder: "Enter up to 100 characters.",
        remaining: " characters left",
        botHelp: "Verification is required to prevent bots.",
        submitting: "Sending...",
        submit: "Submit",
        companyImageAlt: "Company image",
        inquiryOptions: ["Blokit AI inquiry", "WallWall AI inquiry", "Custom AI inquiry"],
        categoryOptions: ["1. Data/Business", "2. Vision/Video", "3. Recommendation/Personalization", "4. NLP/Voice", "5. Robotics", "6. Multimodal", "7. APP/WEB", "8. CRM/ERP", "9. Other: enter directly"],
        errors: {
            agree: "Please agree to the collection and use of personal information.",
            type: "Please select an inquiry type.",
            custom: "Please select a Custom AI inquiry category.",
            etc: "Please enter the other category details.",
            emailRequired: "Please enter your email.",
            emailInvalid: "Please enter a valid email address.",
            phone: "Please enter your phone number.",
            message: "Please enter your message.",
            length: "Message must be 100 characters or fewer.",
            bot: "Please complete bot prevention verification.",
            blocked: "The request cannot be processed.",
            failed: "Failed to send. Please try again later.",
            success: "Your inquiry has been received. We will review it and contact you soon.",
        },
    },
} as const;

export const privacyModalContent = {
    ko: {
        close: "닫기",
        title: "개인정보 수집·이용 동의",
        sections: [
            ["1. 수집하는 개인정보 항목", "회사는 문의 접수를 위해 아래와 같은 개인정보를 수집합니다.", ["필수 항목 : 담당자 이메일, 담당자 연락처, 문의 내용"]],
            ["2. 개인정보의 수집·이용 목적", "수집된 개인정보는 다음의 목적을 위해 이용됩니다.", ["문의 내용 확인 및 상담 응대", "서비스 소개 및 관련 안내 제공", "문의 이력 관리 및 고객 응대 품질 개선"]],
            ["3. 개인정보의 보유 및 이용 기간", "수집된 개인정보는 문의 접수일로부터 최대 3년간 보관되며, 목적 달성 후에는 지체 없이 파기됩니다. 단, 관계 법령에 따라 보존이 필요한 경우 해당 법령에서 정한 기간 동안 보관될 수 있습니다.", []],
            ["4. 동의 거부 권리 및 불이익 안내", "귀하는 개인정보 수집 및 이용에 대한 동의를 거부할 권리가 있습니다. 다만, 동의하지 않으실 경우 문의 접수 및 상담 제공이 제한될 수 있습니다.", []],
            ["5. 개인정보 보호 및 관리", "회사는 수집된 개인정보를 관련 법령 및 내부 관리 기준에 따라 안전하게 관리하며, 개인정보 보호를 위해 필요한 기술적·관리적 보호조치를 시행하고 있습니다.", []],
        ],
    },
    en: {
        close: "Close",
        title: "Consent to Collection and Use of Personal Information",
        sections: [
            ["1. Personal Information Collected", "The company collects the following personal information to receive inquiries.", ["Required items: contact email, contact phone number, inquiry details"]],
            ["2. Purpose of Collection and Use", "Collected personal information is used for the following purposes.", ["Reviewing inquiries and responding to consultation requests", "Providing service introductions and related information", "Managing inquiry history and improving customer support quality"]],
            ["3. Retention and Use Period", "Collected personal information is stored for up to three years from the inquiry date and destroyed without delay after the purpose is fulfilled. If retention is required by law, it may be stored for the legally required period.", []],
            ["4. Right to Refuse Consent", "You have the right to refuse consent to the collection and use of personal information. However, inquiry reception and consultation may be limited if you do not consent.", []],
            ["5. Protection and Management", "The company manages collected personal information safely under applicable laws and internal standards, and implements necessary technical and administrative safeguards.", []],
        ],
    },
} as const;

export const legalContent = {
    ko: {
        privacyTitle: "개인정보처리방침",
        termsTitle: "서비스 이용약관",
        privacySections: [
            ["1. 총칙", "Amuse8 주식회사(이하 '회사')는 'Blokit' 서비스 이용자의 개인정보 보호를 매우 중요하게 여기며, 「개인정보 보호법」 등 관련 법령을 준수하고 있습니다. 회사는 개인정보 처리방침을 통해 이용자의 개인정보가 어떤 용도와 방식으로 이용되고 있으며, 개인정보 보호를 위해 어떤 조치가 취해지고 있는지 알려드립니다."],
            ["2. 수집하는 개인정보의 항목 및 수집방법", "회사는 서비스 제공 및 개선을 위해 이름, 이메일 주소, 비밀번호, 프로필 사진 등 필요한 개인정보를 수집할 수 있으며, 회원가입 또는 서비스 이용 과정에서 직접 입력을 통해 수집합니다."],
            ["3. 개인정보의 수집 및 이용 목적", "개인정보는 Blokit 서비스 제공, 서비스 개선, 개인 맞춤형 AI 모델 성능 향상, 고객 문의 처리 및 공지사항 전달을 위해 이용됩니다."],
            ["4. 개인정보의 보유 및 이용 기간", "회사는 개인정보 수집 및 이용 목적이 달성된 후에는 해당 정보를 지체 없이 파기합니다. 단, 법령에 따라 보존이 필요한 경우 해당 기간 동안 보관합니다."],
            ["5. 개인정보의 파기 절차 및 방법", "개인정보가 불필요하게 되었을 때 전자적 파일은 복구되지 않도록 삭제하고, 기록물 및 출력물은 분쇄하거나 소각합니다."],
            ["6. 개인정보의 제3자 제공", "회사는 원칙적으로 이용자의 개인정보를 외부에 제공하지 않습니다. 다만 이용자 동의가 있거나 법령상 요구가 있는 경우 예외로 합니다."],
            ["7. 이용자 및 법정대리인의 권리", "이용자 및 법정대리인은 언제든지 개인정보 조회, 수정, 가입 해지를 요청할 수 있습니다."],
            ["8. 쿠키", "회사는 맞춤형 서비스 제공을 위해 쿠키를 사용할 수 있으며, 이용자는 브라우저 설정을 통해 쿠키 저장을 허용하거나 거부할 수 있습니다."],
            ["9. 안전성 확보 조치", "회사는 내부관리계획 수립, 직원 교육, 접근 권한 관리, 암호화, 보안 프로그램 설치 등 개인정보 보호 조치를 시행합니다."],
            ["10. 개인정보 보호책임자", "책임자: 신동민 / 직책: CTO / 이메일: dongmin@amuse8.kr"],
            ["11. 처리방침 변경", "이 개인정보 처리방침은 법령 및 회사 내부 정책에 따라 변경될 수 있으며, 변경 사항은 회사 홈페이지를 통해 공지합니다."],
            ["12. 권익 침해 구제 방법", "개인정보 침해 관련 상담은 개인정보침해신고센터, 개인정보 분쟁조정위원회 등 관련 기관을 통해 신청할 수 있습니다."],
        ],
        termsSections: [
            ["제1조(목적)", "본 약관은 Amuse8 Company가 제공하는 Blokit 서비스 이용과 관련하여 회사와 이용자의 권리·의무 및 책임사항, 기타 필요한 사항을 규정합니다."],
            ["제2조(용어의 정의)", "유료서비스, 결제, 콘텐츠 등 본 약관에서 사용하는 주요 용어는 서비스 제공 및 이용 맥락에 따라 정의됩니다."],
            ["제3조(정보의 제공 및 광고의 게재)", "회사는 서비스 이용 중 필요한 정보 및 광고를 전자우편, 문자, 배너 등의 방법으로 제공할 수 있으며, 이용자는 수신을 거부할 수 있습니다."],
            ["제4조(유료서비스의 결제 등)", "이용자는 유료서비스 이용 시 이용대금을 납부해야 하며, 결제수단의 정당한 사용권한 확인이 필요할 수 있습니다."],
            ["제5조(환불)", "환불은 서비스 성격, 이용 내역, 결제 수단 및 관계 법령에 따라 처리됩니다."],
            ["제6조(저작물 저장 및 이용 동의)", "이용자는 서비스를 통해 콘텐츠를 저장하거나 공유할 수 있으며, 이용자가 저장한 콘텐츠의 권리는 이용자에게 있습니다."],
            ["제7조(2차 가공 및 재배포 책임)", "이용자가 콘텐츠를 외부로 공유, 재배포, 2차 가공 또는 상업적으로 활용하는 경우 그 책임은 이용자에게 있습니다."],
            ["제8조(서비스 이용 제한 및 면책)", "기술적 문제 또는 예상치 못한 상황으로 인한 데이터 손실에 대해 회사의 책임은 제한될 수 있으며, 중요한 데이터는 별도 백업을 권장합니다."],
            ["제9조(회원의 책임 및 의무)", "이용자는 타인의 권리를 침해하거나 관련 법령을 위반하지 않아야 하며, 약관 위반 결과는 이용자에게 귀속됩니다."],
            ["제10조(콘텐츠의 관리)", "콘텐츠가 관련 법령을 위반하거나 권리를 침해하는 경우 회사는 필요한 조치를 취할 수 있습니다."],
            ["제11조(관할법원 및 준거법)", "서비스 관련 분쟁은 회사 소재지 관할법원을 관할법원으로 하며, 대한민국 법령을 준거법으로 합니다."],
            ["부칙", "본 약관은 2024.11.15.부터 시행됩니다."],
        ],
    },
    en: {
        privacyTitle: "Privacy Policy",
        termsTitle: "Terms of Service",
        privacySections: [
            ["1. General", "Amuse8 Inc. values the privacy of Blokit users and complies with applicable personal information protection laws. This policy explains how personal information is used and protected."],
            ["2. Information Collected and Collection Method", "The company may collect information required to provide and improve the service, including name, email address, password, and profile image, through sign-up or service use."],
            ["3. Purpose of Use", "Personal information is used to provide Blokit, improve the service, enhance personalized AI model performance, respond to inquiries, and deliver notices."],
            ["4. Retention Period", "The company destroys personal information without delay after the purpose of collection and use is fulfilled, unless retention is required by law."],
            ["5. Destruction Procedure and Method", "Electronic files are securely deleted so they cannot be restored, and printed records are shredded or incinerated."],
            ["6. Third-Party Provision", "The company does not provide personal information to third parties in principle, except with user consent or where required by law."],
            ["7. User Rights", "Users and legal representatives may request access, correction, or account withdrawal at any time."],
            ["8. Cookies", "The company may use cookies to provide personalized services, and users may allow or refuse cookies through browser settings."],
            ["9. Security Measures", "The company implements privacy safeguards such as internal management plans, employee training, access control, encryption, and security programs."],
            ["10. Privacy Officer", "Officer: Dongmin Shin / Title: CTO / Email: dongmin@amuse8.kr"],
            ["11. Policy Changes", "This policy may change according to laws or internal policies, and changes will be announced on the company website."],
            ["12. Remedies", "For privacy infringement counseling, users may contact relevant authorities such as the Personal Information Infringement Report Center or the Personal Information Dispute Mediation Committee."],
        ],
        termsSections: [
            ["Article 1. Purpose", "These terms define the rights, obligations, responsibilities, and other necessary matters between Amuse8 Company and users regarding the Blokit service."],
            ["Article 2. Definitions", "Key terms such as paid service, payment, and content are defined according to the context of service provision and use."],
            ["Article 3. Information and Advertising", "The company may provide necessary information and advertising by email, message, banner, or other methods, and users may opt out where applicable."],
            ["Article 4. Paid Service Payment", "Users must pay the service fee when using paid services, and verification of legitimate payment authority may be required."],
            ["Article 5. Refunds", "Refunds are processed according to service characteristics, usage history, payment method, and applicable laws."],
            ["Article 6. Content Storage and Use", "Users may store or share content through the service, and rights to user-stored content remain with the user."],
            ["Article 7. Secondary Use and Redistribution", "Users are responsible for sharing, redistributing, modifying, or commercially using content outside the service."],
            ["Article 8. Service Restrictions and Disclaimer", "The company's responsibility may be limited for data loss caused by technical issues or unexpected circumstances, and separate backups are recommended for important data."],
            ["Article 9. Member Responsibilities", "Users must not infringe others' rights or violate applicable laws, and users are responsible for results arising from violations."],
            ["Article 10. Content Management", "If content violates laws or infringes rights, the company may take necessary measures."],
            ["Article 11. Jurisdiction and Governing Law", "Disputes are governed by Korean law and the competent court is the court having jurisdiction over the company's location."],
            ["Supplementary Provision", "These terms take effect on November 15, 2024."],
        ],
    },
} as const;
